### ISSUE TITLE
Expecting <eof> near end)

### ISSUE THREAD

**Issue by turbosaab** [ESX-PUBLIC/esx_vehicle_inventory#13]
After installing the resource got error for expecting <eof> near <end>.
I can see two  end) at the bottom of server/main.lua

Removing one of them made resource loading.

**Comment by babydoto** [comment]
yeah i have it too

**Comment by bypazs** [comment]
> After installing the resource got error for expecting near .
> I can see two end) at the bottom of server/main.lua
> 
> Removing one of them made resource loading.

thank you 
you should pull requests :)

**Comment by BruhTrailSupport** [comment]
The resource loaded correctly for me and the SQL file has been ran, but how do i get into the vehicle trunk inventory? Any buttons or commands? I Can't find it..
