### ISSUE TITLE
Update esx

### ISSUE THREAD

**Issue by m0iises19** [ESX-PUBLIC/esx_vehicle_inventory#21]
can you update it to the new version of esx? Thanks in advance

**Comment by rex2630** [comment]
What error are u getting?

**Comment by m0iises19** [comment]
It does not allow items to leave when they are inside the vehicle.

**Comment by rex2630** [comment]
any error on server or client side?

**Comment by m0iises19** [comment]
It does not give any error, it just does not let the objects out of the trunk.

Anyway when I get home I give you more details if any console error

**Comment by m0iises19** [comment]
It does not give any error, it just does not let the objects out of the trunk.

**Comment by manups4e** [comment]
line 258 tonumber(PlayerData.inventory[i].limit) is seen as nil and error is "cannot compare nil with number"

**Comment by m0iises19** [comment]
no open
![noopen](https://user-images.githubusercontent.com/10025085/75816952-6b021e80-5d96-11ea-8216-cc4ae60d2b4b.png)

**Comment by rex2630** [comment]
Did u renamed the script?

**Comment by m0iises19** [comment]
esx_vehicle_inventory-master --> esx_vehicle_inventory

if everything is changed

**Comment by rex2630** [comment]
Yeah, that script needs to be updated for sure, but im not using this script and im not entirely sure how to fix this just yet

**Comment by m0iises19** [comment]
Any similar script that works correctly?

**Comment by rex2630** [comment]
https://github.com/ESX-PUBLIC/esx_adrp_vehicle
