### ISSUE TITLE
Remove items from the bault

### ISSUE THREAD

**Issue by 400CHVRLT** [ESX-PUBLIC/esx_vehicle_inventory#23]
![baul](https://user-images.githubusercontent.com/55306209/79819018-87b2df80-835f-11ea-921c-53d5f0906f46.png)

**Comment by zupdk** [comment]
https://gyazo.com/d18d745abf2c4b7667dd40af299cd152
in client/main.lua change it from limet to weight and then it work

**Comment by Parity-lab** [comment]
Same here
