### ISSUE TITLE
Duping Glitch (Not the same as the other)

### ISSUE THREAD

**Issue by Bezhaa** [ESX-PUBLIC/esx_vehicle_inventory#9]
Spamming the "Submit" button or spamming the Enter key, will put duplicate the items into the trunk.

Say you have 10 meth bags, 0 in the trunk. 
You spam "Submit" when putting 10 inside the trunk and you'll have 40 meth bags inside of the vehicle.

Not sure where to start with fixing this, any ideas?

**Comment by Sidusol** [comment]
I tried to fix it for a long time and I can't do that... some guy answered me "that is not a problem, you just have to make sure that you will the UI after you put a item inside" but I have no idea what he;s talking about :D

**Comment by Bezhaa** [comment]
Hmm, I'm gonna have to take a look and see what I can do.

**Comment by OhTanoshi** [comment]
Just add a 2-5 second delay on storing and removing items

**Comment by Sidusol** [comment]
I have fixed that other way, also added function that checks if player opening the trunks has keys to it.

**Comment by Bezhaa** [comment]
Is it possible you could share how you solved it? I'm fairly new to this stuff. I would appreciate it dearly.

**Comment by JaroSound** [comment]
Any fix yet?
